[package]
name = "mincaml-tool"
version = "0.1.0"
authors = ["Shahryar Tariq <st876@cornell.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.0"
pest_derive = "2.0"
